[main]
experiments = 0
epsilon = 0.05
stoptime = 100,years
slaves = 4
executor = serial
logginglevel = info
submodels = X
signals = sigA,sigB
watchdog = 10,mins
monitorperiod = 0.05,float
monitorflag = True,bool
deltatime = 95,mins

[sigA]
#function = 4*math.sin(2 * 3.14 * t * 1.80E-4)
function = 0.000005*t+0.0000000003+a*0000000000.1
conditions = [('X_C1','sigA > 70')],conditions

[sigB]
function = 4*math.sin(2 * 3.14 * t * 1.80E-9+a*0.000000000001)
conditions = [('X_C2','sigB > 3.999999')],conditions




[X]
structure = [('C1', 2, 2, 3.6E7),('C2', 2, 2, 3.6E7),('C3', 2, 2, 2.6E7)],hwconf