[main]
experiments = 0
epsilon = 0.05
stoptime = 50,years
slaves = 4
executor = serial
logginglevel = info
submodels = X
signals = sigA
watchdog = 10,mins
monitorperiod = 0.05,float
monitorflag = True,bool
deltatime = 10,mins

[sigA]
#function = 4*math.sin(2 * 3.14 * t * 1.80E-4)
function = 0.000005*t+0.000003
conditions = [('X_C1','sigA > 70')],conditions


[X]
structure = [('C1', 2, 2, 3.6E15),('C2', 2, 2, 3.6E8),('C3', 2, 2, 3.6E8)],hwconf