[main]
experiments = 0
epsilon = 0.05
stoptime = 100,years
slaves = 4
executor = serial
logginglevel = info
submodels = X
signals = sigA,sigB,sigC
watchdog = 10,mins
monitorperiod = 0.05,float
monitorflag = True,bool
deltatime = 95,mins

[sigA]
#function = 4*math.sin(2 * 3.14 * t * 1.80E-4)
function = 0.000005*t+0.000003+(1E-10)*a
conditions = [('X_C1','sigA > 70')],conditions

[sigB]
function = 4*math.sin(2 * 3.14 * t * 1.80E-8+(1E-10)*a)
conditions = [('X_C2','sigB > 3.99999')],conditions

[sigC]
#function = 4*math.sin(2 * 3.14 * t * 1.80E-4)
function = 0.000005*t+0.000003+(1E-10)*a
conditions = [('X_C3','sigC > 85')],conditions


[X]
structure = [('C1', 2, 2, 1E7),('C2', 2, 2, 1E7),('C3', 2, 2, 0.9E7)],hwconf

[C1]
structure = [('X_C10',5E7),('X_C11',5E7)],hwconf

[C2]
structure = [('X_C20',5E7),('X_C21',5E7)],hwconf

[C3]
structure = [('X_C30',3.5E7),('X_C31',3.5E7)],hwconf